Repository gnosis/dex-services, pull requests merged in 2020-08, with the labels that each got.

#1206 Update infallible price source with prices
  core/src/orderbook.rs
  core/src/price_estimation.rs
  core/src/price_estimation/average_price_source.rs
  core/src/token_info.rs
  price-estimator/src/filter.rs
  price-estimator/src/infallible_price_source.rs
  price-estimator/src/main.rs
  price-estimator/src/models.rs
  price-estimator/src/orderbook.rs
  price-estimator/src/solver_rounding_buffer.rs
Labels: Price Estimator, merge when green

#1235 Document beste-ask-price route
  price-estimator/README.md
Labels: Price Estimator, merge when green

#1238 Remove unused method in StableXContract implementation
  core/src/contracts/stablex_contract.rs
Labels: merge when green, trivial

#1234 Clean up: Removing all shouldEstimatePrice appearances
  README.md
  core/src/token_info/hardcoded.rs
  driver/src/main.rs
Labels: merge when green

#1229 Parallelize batch processing in E2E scripts
  Cargo.lock
  e2e/Cargo.toml
  e2e/src/bin/historic_prices.rs
  e2e/src/bin/historic_trades.rs
  e2e/src/cmd.rs
Labels: merge when green

#1239 Add benchmarking section to price estimator README
  price-estimator/README.md
Labels: Price Estimator, merge when green, trivial

#1240 Handle internal server errors
  price-estimator/src/filter.rs
Labels: Price Estimator, merge when green, trivial

#1247 [Trivial] Log verified solutions with correct stage
  core/src/metrics/stablex_metrics.rs
Labels: merge when green, trivial

#1245 Do not keep retrying to fetch token infos if call reverts
  core/src/price_estimation.rs
  core/src/token_info/cached.rs
  price-estimator/src/main.rs
Labels: merge when green

#1250 Make use of new get_token_infos
  core/src/price_estimation.rs
  core/src/price_estimation/clients/generic_client.rs
  core/src/price_estimation/clients/kraken.rs
Labels: merge when green

#1231 parallelize historic trades script
  e2e/src/bin/historic_prices.rs
  e2e/src/bin/historic_trades.rs
  e2e/src/cmd.rs
Labels: merge when green

#1246 Use slightly higher min_avg_fee compared to max_gas_price
  core/src/economic_viability.rs
  driver/src/main.rs
Labels: merge when green

#1253 Fix how min average fee is passed to solver
  core/src/economic_viability.rs
  core/src/price_finding/optimization_price_finder.rs
Labels: merge when green

#689 Implement contract deployment in Rust
  Cargo.lock
  Cargo.toml
  contracts/Cargo.toml
  contracts/README.md
  contracts/build.rs
  contracts/src/bin/deploy.rs
  contracts/src/lib.rs
  contracts/src/paths.rs
Labels: merge when green

#1236 Create infallible price source with real token data and price sources
  price-estimator/src/filter.rs
  price-estimator/src/infallible_price_source.rs
  price-estimator/src/main.rs
  price-estimator/src/orderbook.rs
Labels: Price Estimator, merge when green

#1254 Use new contracts crate in e2e and core crates
  Cargo.lock
  core/Cargo.toml
  core/build.rs
  core/src/contracts/stablex_contract.rs
  core/src/history.rs
  core/src/history/events.rs
  core/src/orderbook/streamed/state.rs
  core/src/orderbook/streamed/updating_orderbook.rs
  e2e/Cargo.toml
  e2e/src/bin/historic_trades.rs
  e2e/src/lib.rs
  e2e/src/stablex.rs
  e2e/tests/stablex_test.rs
Labels: merge when green

#1258 Fix unnecessary rebuilds
  Cargo.lock
  contracts/Cargo.toml
  contracts/build.rs
  contracts/src/bin/deploy.rs
Labels: merge when green

#1255 Use Rust deploy script for CI
  .travis.yml
  ci/setup_contracts.sh
  contracts/README.md
  scripts/setup_contracts.sh
Labels: merge when green

#1262 [Hotfix] Fix price estimator deployment
  price-estimator/docker/Dockerfile
Labels: merge when green, trivial

#1265 [Trivial] adjust gas amount for solution submission
  core/src/contracts/stablex_contract.rs
Labels: trivial

#1266 Add benchmarking instructions
  pricegraph/README.md
Labels: documentation, merge when green, trivial

#1270 Fix order_for_limit_price not returning None
  pricegraph/src/api/price_estimation.rs
Labels: merge when green, pricegraph

#1251 Specialize get_token_infos for TokenInfoCache
  core/src/token_info/cached.rs
Labels: merge when green

#1271 Port pricegraph `fetch` data script to Rust
  Cargo.lock
  Cargo.toml
  contracts/src/lib.rs
  pricegraph/README.md
  pricegraph/data/Cargo.toml
  pricegraph/data/fetch.js
  pricegraph/data/fetch.rs
Labels: merge when green, pricegraph

#1278 Port pricegraph `convert` script to Rust
  .gitignore
  Cargo.lock
  pricegraph/README.md
  pricegraph/data/Cargo.toml
  pricegraph/data/README.md
  pricegraph/data/convert.js
  pricegraph/data/convert.rs
  pricegraph/data/fetch.rs
  pricegraph/data/package.json
  pricegraph/data/yarn.lock
Labels: merge when green, pricegraph

#1283 Shared logger in price estimator.
  Cargo.lock
  price-estimator/Cargo.toml
  price-estimator/src/main.rs
Labels: Price Estimator, merge when green

#1289 Add SystemTime utilities
  core/src/lib.rs
  core/src/models/batch_id.rs
  core/src/time.rs
Labels: merge when green, trivial

#1261 Use new rounding buffer in estimate_buy_amount route
  price-estimator/src/filter.rs
  price-estimator/src/infallible_price_source.rs
  price-estimator/src/main.rs
  price-estimator/src/orderbook.rs
Labels: Price Estimator, merge when green

#1267 Use new rounding buffer for estimated-amounts-at-price route
  price-estimator/src/amounts_at_price.rs
  price-estimator/src/filter.rs
  price-estimator/src/main.rs
Labels: Price Estimator, merge when green

#1286 Use new rounding buffer in estimate-best-ask-price route
  price-estimator/src/filter.rs
Labels: Price Estimator, merge when green

#1285 Allow minimum solution submit time to be set
  core/src/driver/scheduler.rs
  core/src/driver/scheduler/evm.rs
  core/src/driver/scheduler/system.rs
  core/src/driver/stablex_driver.rs
  driver/src/main.rs
Labels: config change, merge when green

#1279 Refactor query parameter parsing to allow mutually exclusive values
  price-estimator/src/filter.rs
  price-estimator/src/models.rs
  price-estimator/src/models/query.rs
  price-estimator/src/orderbook.rs
Labels: Price Estimator, merge when green

#1294 Token by symbol or address
  price-estimator/src/filter.rs
  price-estimator/src/models.rs
  price-estimator/src/models/currency_pair.rs
Labels: Price Estimator, merge when green

#1300 Unit parameter with default
  price-estimator/README.md
  price-estimator/src/filter.rs
  price-estimator/src/models/query.rs
Labels: merge when green

#1288 Block number and timestamp query parameters
  price-estimator/src/models/query.rs
  price-estimator/src/orderbook.rs
Labels: merge when green

#1298 Pass extra_rounding_buffer_factor as command line argument
  price-estimator/src/filter.rs
  price-estimator/src/main.rs
  price-estimator/src/orderbook.rs
Labels: merge when green

#1302 include warp logs by default
  price-estimator/src/main.rs
Labels: Price Estimator, merge when green, trivial

#1303 only use one root logger
  price-estimator/src/filter.rs
  price-estimator/src/main.rs
Labels: Price Estimator, merge when green, trivial

#1299 Single error type
  price-estimator/src/error.rs
  price-estimator/src/filter.rs
Labels: merge when green

#1296 Add openapi documentation
  price-estimator/openapi.yml
Labels: Price Estimator, merge when green

#1307 Record missing price estimates
  e2e/src/bin/historic_prices.rs
Labels: merge when green

#1308 Estimate considered good if it is within 1 order of magnitude
  e2e/src/bin/historic_prices.rs
Labels: merge when green

#1310 Remove non openapi documentation
  price-estimator/README.md
  price-estimator/openapi.yml
Labels: Price Estimator, merge when green

#1309 Classify false negatives
  e2e/src/bin/historic_trades.rs
Labels: merge when green

#1304 Health endpoint
  price-estimator/src/health.rs
  price-estimator/src/main.rs
Labels: Price Estimator, merge when green

#1311 Implement `GasPriceEstimating` for `Web3`
  core/src/economic_viability.rs
  core/src/gas_price.rs
  core/src/gas_price/eth_node.rs
  core/src/gas_price/gas_station.rs
  core/src/lib.rs
  core/src/solution_submission.rs
  core/src/solution_submission/retry.rs
  driver/src/main.rs
Labels: merge when green

#1314 [Easy] Move MarketResults into its own file
  price-estimator/src/models.rs
  price-estimator/src/models/markets_results.rs
Labels: merge when green

#1317 Docker setup for Mac
  .dockerignore
  docker-compose.yml
  driver/docker/rust/Dockerfile.debug
Labels: merge when green

#1327 Update README
  .dockerignore
  README.md
  driver/common-mainnet.env
  driver/common-rinkeby.env
  driver/docker-compose.mainnet.yml
  driver/docker-compose.rinkeby.yml
Labels: merge when green

#1315 Implement BaseUnits for Market route
  Cargo.lock
  price-estimator/Cargo.toml
  price-estimator/openapi.yml
  price-estimator/src/filter.rs
  price-estimator/src/models/markets_results.rs
Labels: merge when green

#1313 Document how to use openapi locally
  price-estimator/README.md
  price-estimator/src/main.rs
Labels: Price Estimator, merge when green

#1319 Introduce trait for mocking current time
  core/src/driver/scheduler/system.rs
  core/src/util.rs
Labels: merge when green

#1320 Split run into two functions internally
  core/src/driver/stablex_driver.rs
Labels: merge when green

#1323 Search by symbol
  core/src/macros.rs
  core/src/token_info.rs
  core/src/token_info/cached.rs
  core/src/token_info/hardcoded.rs
  price-estimator/src/main.rs
  price-estimator/src/models/currency_pair.rs
Labels: Price Estimator, config change, merge when green

#1321 Use real result type
  core/src/driver/scheduler/evm.rs
  core/src/driver/scheduler/system.rs
  core/src/driver/stablex_driver.rs
Labels: merge when green

#1322 Handle timing of solution submission in scheduler
  core/src/driver/scheduler/evm.rs
  core/src/driver/scheduler/system.rs
  core/src/driver/stablex_driver.rs
Labels: merge when green

#1325 Replace crossbream scoped thread with asycnstd task
  Cargo.lock
  core/Cargo.toml
  core/src/contracts/stablex_contract.rs
  core/src/driver/scheduler.rs
  core/src/driver/scheduler/evm.rs
  core/src/driver/scheduler/system.rs
  core/src/driver/stablex_driver.rs
  core/src/orderbook/onchain_filtered_orderbook.rs
  core/src/orderbook/paginated_orderbook.rs
  core/src/orderbook/streamed/updating_orderbook.rs
  core/src/price_finding.rs
  core/src/solution_submission.rs
  core/src/solution_submission/retry.rs
  driver/src/main.rs
Labels: merge when green

#1333 Print default backtrace in additon to error log on panic
  core/src/logging.rs
Labels: merge when green

#1335 separate HTTP server from metrics encoding
  core/src/http_server.rs
  core/src/http_server/routing.rs
  core/src/lib.rs
  core/src/metrics.rs
  core/src/metrics/metrics_handler.rs
  core/src/metrics/metrics_server.rs
  driver/src/main.rs
  price-estimator/src/main.rs
Labels: config change, merge when green

#1332 remove paginated orderbook reader
  core/src/orderbook.rs
  core/src/orderbook/auction_data_reader.rs
  core/src/orderbook/paginated_orderbook.rs
Labels: merge when green, trivial

#1340 Remove old orderbook reading implementations
  README.md
  core/src/macros.rs
  core/src/orderbook.rs
  core/src/orderbook/auction_data_reader.rs
  core/src/orderbook/onchain_filtered_orderbook.rs
  core/src/orderbook/shadow_orderbook.rs
  core/src/token_info/hardcoded.rs
  driver/src/main.rs
  price-estimator/src/filter.rs
  price-estimator/src/orderbook.rs
Labels: config change, merge when green, trivial

#1305 introduce HTTP health reporting endpoint that runs in a backgroun thread
  core/src/health.rs
  core/src/http_server.rs
  core/src/http_server/routing.rs
  core/src/lib.rs
  driver/src/main.rs
  price-estimator/src/health.rs
  price-estimator/src/main.rs
Labels: merge when green

#1337 Add hosted price estimator docs to readme
  price-estimator/README.md
Labels: merge when green

#1339 Move solution submission batch id check to scheduler
  core/src/driver/scheduler.rs
  core/src/driver/scheduler/system.rs
  core/src/solution_submission.rs
Labels: merge when green

#1341 BasUnit support for best ask price route
  price-estimator/openapi.yml
  price-estimator/src/filter.rs
  price-estimator/src/models.rs
Labels: merge when green

#1349 Add query parameter to filter addresses out of the orderbook
  price-estimator/openapi.yml
  price-estimator/src/filter.rs
  price-estimator/src/models/query.rs
  price-estimator/src/orderbook.rs
Labels: Price Estimator

#1360 Refactor evm scheduler
  core/src/driver/scheduler/evm.rs
Labels: merge when green

#1361 Add address to TokenBaseInfo
  README.md
  core/src/price_estimation.rs
  core/src/price_estimation/clients/dexag.rs
  core/src/price_estimation/clients/generic_client.rs
  core/src/price_estimation/clients/kraken.rs
  core/src/price_estimation/clients/oneinch.rs
  core/src/token_info.rs
  core/src/token_info/cached.rs
  core/src/token_info/hardcoded.rs
  core/src/token_info/onchain.rs
  driver/src/main.rs
  price-estimator/openapi.yml
  price-estimator/src/infallible_price_source.rs
  price-estimator/src/models.rs
  price-estimator/src/models/currency_pair.rs
  price-estimator/src/models/markets_results.rs
Labels: merge when green

#1366 Add e2e script docuemtnation
  e2e/README.md
Labels: merge when green

#1367 Implement earliest solution submit time for evm scheduler
  core/src/driver/scheduler/evm.rs
Labels: merge when green

#1356 fetch batch for block number
  core/src/history/events.rs
  core/src/orderbook/streamed/updating_orderbook.rs
Labels: merge when green

#1357 Handle block queries
  price-estimator/README.md
  price-estimator/openapi.yml
  price-estimator/src/models/query.rs
  price-estimator/src/orderbook.rs
Labels: merge when green

#1372 Fix sleep not being awaited
  core/src/driver/scheduler/system.rs
  core/src/solution_submission.rs
  core/src/util.rs
Labels: merge when green

#1376 Panic intead of endlessly allocating.
  pricegraph/src/graph/shortest_paths.rs
  pricegraph/src/orderbook.rs
Labels: merge when green, trivial

#1373 Report healthiness at the start of the next batch
  core/src/driver/scheduler.rs
  core/src/driver/scheduler/evm.rs
  core/src/driver/scheduler/system.rs
  core/src/health.rs
  driver/src/main.rs
Labels: merge when green

#1374 Use integer weights
  pricegraph/src/orderbook.rs
  pricegraph/src/orderbook/scalar.rs
  pricegraph/src/orderbook/weight.rs
Labels: merge when green

#1380 Convert BoxFuture to async_trait
  Cargo.lock
  services-core/Cargo.toml
  services-core/src/economic_viability.rs
  services-core/src/gas_price.rs
  services-core/src/gas_price/eth_node.rs
  services-core/src/gas_price/gas_station.rs
  services-core/src/solution_submission.rs
  services-core/src/solution_submission/retry.rs
Labels: merge when green
