Repository gnosis/dex-services, pull requests merged in 2020-03, with the labels that each got.

#594 [Easy] No longer receiving external price info via solver && clean up for token_data
  README.md
  driver/src/main.rs
  driver/src/price_finding/optimization_price_finder.rs
Labels: merge when green

#606 Only count prices > 0 in solution for metrics
  driver/src/metrics/stablex_metrics.rs
Labels: merge when green

#608 Refactor `NaiveSolver::find_prices` into smaller functions
  driver/src/price_finding/naive_solver.rs
Labels: cleanup

#622 [Trivial] Add contracts folder to shared volume in docker-compose
  docker-compose.yml
Labels: merge when green

#596 Use a shared HTTP client implementation
  driver/src/contracts/mod.rs
  driver/src/gas_station.rs
  driver/src/http.rs
  driver/src/main.rs
  driver/src/price_estimation/dexag/api.rs
  driver/src/price_estimation/dexag/mod.rs
  driver/src/price_estimation/kraken.rs
  driver/src/price_estimation/kraken/api.rs
  driver/src/price_estimation/mod.rs
  driver/src/transport.rs
Labels: merge when green

#595 Calculate time limit for solver based on remaining time in batch.
  README.md
  driver/src/driver/scheduler.rs
  driver/src/driver/stablex_driver.rs
  driver/src/main.rs
  driver/src/price_finding/mod.rs
  driver/src/price_finding/naive_solver.rs
  driver/src/price_finding/optimization_price_finder.rs
  driver/src/price_finding/price_finder_interface.rs
Labels: merge when green

#641 Don't advance EVM time when waiting for solution
  e2e/src/common.rs
  e2e/tests/stablex_test.rs
Labels: merge when green

#636 Use mockall with trait instead of functions
  driver/src/price_finding/optimization_price_finder.rs
Labels: cleanup

#638 Http Metrics Revised
  driver/src/gas_station.rs
  driver/src/http.rs
  driver/src/main.rs
  driver/src/metrics/http_metrics.rs
  driver/src/metrics/mod.rs
  driver/src/price_estimation/dexag/api.rs
  driver/src/price_estimation/kraken/api.rs
  driver/src/transport.rs
Labels: merge when green

#644 Evm scheduler
  README.md
  common-mainnet.env
  common-rinkeby.env
  common.env
  driver/src/contracts/stablex_contract.rs
  driver/src/driver/scheduler.rs
  driver/src/driver/scheduler/evm.rs
  driver/src/driver/scheduler/system.rs
  driver/src/main.rs
  driver/src/orderbook/filtered_orderbook.rs
  e2e/src/common.rs
  e2e/tests/stablex_test.rs
Labels: merge when green

#647 Discount orderbook retrieval from the solver time.
  driver/src/driver/stablex_driver.rs
Labels: merge when green

#653 Use `--help` output to generate readme configuration options section
  README.md
Labels: cleanup

#654 New solver command line interface
  .travis.yml
  driver/src/price_finding/optimization_price_finder.rs
Labels: merge when green

#658 Simplify AccountState
  driver/src/models/account_state.rs
  driver/src/orderbook/paginated_auction_data_reader.rs
  driver/src/price_finding/naive_solver.rs
  driver/src/price_finding/optimization_price_finder.rs
Labels: cleanup, merge when green
