Repository gnosis/dex-services, pull requests merged in 2020-07, with the labels that each got.

#1057 [TokenInfo 1] Extract TokenData into TokenInfoFetching trait
  core/src/lib.rs
  core/src/price_estimation.rs
  core/src/price_estimation/data.rs
  core/src/price_estimation/dexag.rs
  core/src/price_estimation/kraken.rs
  core/src/token_info.rs
  core/src/token_info/hardcoded.rs
  driver/src/main.rs
Labels: merge when green

#1065 [TokenInfo 2] Making TokenInfoFetching async
  core/src/macros.rs
  core/src/price_estimation.rs
  core/src/price_estimation/dexag.rs
  core/src/price_estimation/kraken.rs
  core/src/price_estimation/threaded_price_source.rs
  core/src/token_info.rs
  core/src/token_info/hardcoded.rs
Labels: merge when green

#1066 compute historic auction elements and settlement
  core/src/history.rs
  core/src/history/events.rs
Labels: merge when green

#1052 Handle node going back in time more gracefully
  core/src/orderbook/streamed/updating_orderbook.rs
Labels: merge when green

#1062 Change ordering of transitive orders in price estimator response
  price-estimator/src/models.rs
Labels: Price Estimator, merge when green

#1067 Added estimaged exchange rate API
  price-estimator/src/filter.rs
  price-estimator/src/models.rs
Labels: merge when green

#1069 Historic prices with pricegraph spread.
  Cargo.lock
  core/src/history.rs
  core/src/history/events.rs
  core/src/models/batch_id.rs
  e2e/Cargo.toml
  e2e/src/bin/historic_prices.rs
Labels: merge when green

#1054 Deploy in release mode
  .dockerignore
  .travis.yml
  Cargo.toml
  docker/rust/Dockerfile
Labels: merge when green

#1068 PriorityPriceSource
  core/src/price_estimation.rs
  core/src/price_estimation/priority_price_source.rs
Labels: merge when green

#1070 Implementing PriceSource for TokenData
  core/src/price_estimation.rs
  core/src/token_info/hardcoded.rs
  driver/src/main.rs
Labels: merge when green

#1071 Use two-stage model for standard solver
  .travis.yml
  core/src/price_finding/price_finder_interface.rs
Labels: merge when green

#1040 Use generic client for dex.ag price fetching
  core/src/price_estimation.rs
  core/src/price_estimation/clients.rs
  core/src/price_estimation/clients/dexag.rs
  core/src/price_estimation/clients/dexag/api.rs
  core/src/price_estimation/clients/generic_client.rs
  core/src/price_estimation/clients/kraken.rs
  core/src/price_estimation/clients/kraken/api.rs
Labels: merge when green

#1074 Cached TokenInfoFetching
  core/src/token_info.rs
  core/src/token_info/cached.rs
Labels: merge when green

#1077 Add 1inch API
  core/src/metrics/http_metrics.rs
  core/src/price_estimation.rs
  core/src/price_estimation/clients.rs
  core/src/price_estimation/clients/dexag/api.rs
  core/src/price_estimation/clients/oneinch.rs
  core/src/price_estimation/clients/oneinch/api.rs
Labels: merge when green

#1080 [Easy] Fix PriceSource priority order
  core/src/price_estimation.rs
Labels: merge when green

#1076 Onchain token fetching integration
  core/src/orderbook/streamed.rs
  core/src/price_estimation.rs
  core/src/price_estimation/orderbook_based.rs
  core/src/price_estimation/priority_price_source.rs
  core/src/token_info/cached.rs
  core/src/token_info/hardcoded.rs
  driver/src/main.rs
Labels: merge when green

#1078 Remove driver docker container special case for driver compilation
  .travis.yml
  README.md
  docker-compose.best-ring-solver.yml
  docker-compose.open-solver.yml
  docker-compose.private-solver.yml
  docker-compose.yml
  docker/rust/Dockerfile
  e2e/README.md
Labels: merge when green

#1079 Move driver related docker files into driver folder
  .dockerignore
  .travis.yml
  README.md
  docker-compose.yml
  driver/common-mainnet.env
  driver/common-rinkeby.env
  driver/common.env
  driver/docker-compose.best-ring-solver.yml
  driver/docker-compose.mainnet.yml
  driver/docker-compose.open-solver.yml
  driver/docker-compose.private-solver.yml
  driver/docker-compose.rinkeby.yml
  driver/docker/deploy.sh
  driver/docker/rust/Dockerfile
  driver/docker/rust/release/open_solver/Dockerfile
  driver/docker/rust/release/private_solver/Dockerfile
  driver/docker/rust/tini
  driver/docker/truffle/Dockerfile
  driver/docker/truffle/run.sh
Labels: merge when green

#1088 Use two-stage model in BestRingSolver.
  core/src/price_finding/price_finder_interface.rs
Labels: merge when green

#1085 Make sure gas price is increased by at least minimum factor
  core/src/solution_submission.rs
Labels: merge when green

#1092 Benchmark Pricegraph API
  pricegraph/Cargo.toml
  pricegraph/benches/orderbook.rs
  pricegraph/benches/pricegraph.rs
  pricegraph/data/mod.rs
  pricegraph/src/lib.rs
  pricegraph/src/orderbook.rs
  pricegraph/wasm/src/lib.rs
Labels: pricegraph

#1094 Use `node_bound` to check for invalid tokens.
  pricegraph/src/orderbook.rs
Labels: merge when green, pricegraph, trivial

#1093 Introduce `Market` struct
  price-estimator/src/filter.rs
  price-estimator/src/models.rs
  pricegraph/benches/pricegraph.rs
  pricegraph/fuzz/fuzz_targets/pricegraph.rs
  pricegraph/src/lib.rs
  pricegraph/src/orderbook.rs
Labels: pricegraph

#1091 Simplify retry_with_gas_price_increase
  core/src/solution_submission.rs
Labels: merge when green

#1104 Use common `Order` to `Element` conversion
  core/src/history.rs
  core/src/models/order.rs
  price-estimator/src/orderbook.rs
Labels: trivial

#1095 Implement atoms=false for estimated_buy_amount
  core/src/token_info.rs
  core/src/token_info/cached.rs
  price-estimator/README.md
  price-estimator/src/filter.rs
  price-estimator/src/main.rs
  price-estimator/src/models.rs
Labels: Price Estimator, merge when green

#1096 Refactor Transitive Order Reducing Loops
  pricegraph/src/lib.rs
  pricegraph/src/orderbook.rs
  pricegraph/src/orderbook/flow.rs
Labels: merge when green, pricegraph

#1097 Added errors for operations that require reduced orderbooks
  pricegraph/src/graph/bellman_ford.rs
  pricegraph/src/lib.rs
  pricegraph/src/orderbook.rs
Labels: merge when green, pricegraph

#1051 Calculate rounding buffer like solver
  price-estimator/src/main.rs
  price-estimator/src/solver_rounding_buffer.rs
Labels: Price Estimator, merge when green

#1098 Use `Flow` Instead of Capacity/Xrate Tuple
  pricegraph/src/orderbook.rs
  pricegraph/src/orderbook/flow.rs
Labels: merge when green, pricegraph

#1102 Allow hardcoded token info
  price-estimator/src/main.rs
Labels: merge when green

#1103 Use types to represent prices and exchange rates
  core/src/models/order.rs
  pricegraph/src/encoding.rs
  pricegraph/src/lib.rs
  pricegraph/src/orderbook.rs
  pricegraph/src/orderbook/flow.rs
  pricegraph/src/orderbook/order.rs
  pricegraph/src/orderbook/scalar.rs
Labels: merge when green, pricegraph

#1101 Implement atoms=false for estimated_amounts_at_price
  price-estimator/README.md
  price-estimator/src/filter.rs
Labels: Price Estimator, merge when green

#1107 Use Mergify for merge-when-green
  .github/merge-when-green.yml
  .mergify.yml
Labels: merge when green

#1108 Cache all token infos in parallel
  core/src/macros.rs
  core/src/token_info/cached.rs
  price-estimator/src/main.rs
Labels: merge when green

#1112 Fix `panic` because of partially reduced orderbook graph when computing transitive orderbook
  pricegraph/src/encoding.rs
  pricegraph/src/lib.rs
  pricegraph/src/orderbook.rs
  pricegraph/src/test.rs
Labels: pricegraph

#1114 Use pricegraph macro for tests
  pricegraph/src/lib.rs
Labels: pricegraph, trivial

#1113 Serialize price estimator token ids as numbers istead of strings
  price-estimator/README.md
  price-estimator/src/models.rs
Labels: merge when green

#1089 Cancel transaction when solution submission time expires
  core/src/contracts/stablex_contract.rs
  core/src/driver/scheduler.rs
  core/src/models/batch_id.rs
  core/src/solution_submission.rs
Labels: merge when green

#1110 Update solver version to v0.8.1
  .travis.yml
Labels: merge when green

#1119 Reuse compare non-NaN assertion
  pricegraph/src/num.rs
Labels: pricegraph, trivial

#1115 [Mergify] auto merge dependabot PRs
  .mergify.yml
Labels: merge when green

#1117 Introduce `Ring` flow type and refactor transitive orderbook computation
  pricegraph/src/lib.rs
  pricegraph/src/orderbook.rs
  pricegraph/src/orderbook/flow.rs
Labels: merge when green, pricegraph

#1118 Separate API operations into modules
  pricegraph/src/api.rs
  pricegraph/src/api/price_estimation.rs
  pricegraph/src/api/transitive_orderbook.rs
  pricegraph/src/lib.rs
  pricegraph/src/num.rs
  pricegraph/src/test.rs
Labels: merge when green, pricegraph

#1121 Promote transitive orderbook implementation to Pricegraph
  pricegraph/src/api.rs
  pricegraph/src/api/transitive_orderbook.rs
  pricegraph/src/orderbook.rs
Labels: merge when green, pricegraph

#1131 higher gas_cap limit
  core/src/solution_submission.rs
Labels: merge when green, trivial

#1122 Promote price and order estimates to Pricegraph
  pricegraph/src/api/price_estimation.rs
  pricegraph/src/lib.rs
  pricegraph/src/orderbook.rs
  pricegraph/src/orderbook/reduced.rs
  pricegraph/src/test.rs
Labels: merge when green, pricegraph

#1124 Rename methods for more consistent language
  core/src/price_estimation/orderbook_based.rs
  e2e/src/bin/historic_prices.rs
  price-estimator/src/filter.rs
  pricegraph/benches/pricegraph.rs
  pricegraph/src/api/price_estimation.rs
  pricegraph/wasm/src/lib.rs
Labels: merge when green, pricegraph, trivial

#1128 Reject atoms=false if not implemented
  price-estimator/src/filter.rs
Labels: merge when green

#1116 Explicitly set nonce in solution submission transaction
  core/src/contracts/stablex_contract.rs
  core/src/solution_submission.rs
Labels: merge when green

#1135 Make price estimator orderbook use Box instead of generics
  price-estimator/src/filter.rs
  price-estimator/src/main.rs
  price-estimator/src/orderbook.rs
Labels: Price Estimator, merge when green

#1140 Fix limit price estimation regression
  pricegraph/src/api/price_estimation.rs
Labels: merge when green, pricegraph, trivial

#1136 Refactor price estimator rounding buffer calculation
  price-estimator/src/solver_rounding_buffer.rs
Labels: Price Estimator, merge when green

#1138 implement historic price estimates
  price-estimator/README.md
  price-estimator/src/error.rs
  price-estimator/src/filter.rs
  price-estimator/src/main.rs
  price-estimator/src/models.rs
  price-estimator/src/orderbook.rs
Labels: Price Estimator, merge when green

#1137 Handle tokens without price in rounding buffer calculation
  price-estimator/src/solver_rounding_buffer.rs
Labels: Price Estimator, merge when green

#1158 Add log messages for price source API errors
  core/src/models/tokens.rs
  core/src/price_estimation/clients/generic_client.rs
Labels: merge when green, trivial

#1162 Add JSON body to error context when failing to parse HTTP response
  core/src/http.rs
Labels: merge when green, trivial

#1139 Refactor orderbook based price source to be more generic
  core/src/price_estimation/orderbook_based.rs
Labels: merge when green

#1151 Split solution submission into two files
  core/src/solution_submission.rs
  core/src/solution_submission/retry.rs
Labels: cleanup, merge when green

#1161 Adjust price source error messages.
  core/src/price_estimation/clients/dexag/api.rs
  core/src/price_estimation/clients/generic_client.rs
  core/src/price_estimation/clients/oneinch/api.rs
Labels: merge when green, trivial

#1159 Increase 1Inch and Dex.ag HTTP timeout
  core/src/price_estimation/clients/dexag/api.rs
  core/src/price_estimation/clients/oneinch/api.rs
Labels: merge when green, trivial

#1166 Increase gas price slower but higher
  core/src/solution_submission.rs
  core/src/solution_submission/retry.rs
  pricegraph/src/lib.rs
Labels: merge when green

#1165 Make sure gas station gas price does not decrease
  core/src/solution_submission/retry.rs
Labels: merge when green

#1163 Introduce mockable trait for async sleeping
  core/src/util.rs
Labels: merge when green

#1164 Use more explicit return type for noop transaction
  core/src/contracts/stablex_contract.rs
  core/src/solution_submission.rs
Labels: merge when green

#1144 Estimate price based on available buy token liquidity
  pricegraph/src/api/price_estimation.rs
  pricegraph/src/lib.rs
  pricegraph/src/num.rs
  pricegraph/src/orderbook.rs
  pricegraph/src/orderbook/scalar.rs
  pricegraph/src/test.rs
Labels: merge when green, pricegraph

#1142 Price Estimator scaffolding for pricegraph with rounding buffer applied
  price-estimator/src/filter.rs
  price-estimator/src/orderbook.rs
Labels: Price Estimator, merge when green

#1152 Turn retry_with_gas_price_increase into a mockable trait
  core/src/solution_submission.rs
  core/src/solution_submission/retry.rs
Labels: merge when green

#1176 Write to pricegraph without rounding buffer on update
  price-estimator/src/orderbook.rs
Labels: Price Estimator, merge when green, trivial

#1174 Implement comparison traits for limit prices
  pricegraph/src/orderbook/scalar.rs
Labels: merge when green, pricegraph, trivial

#1175 Add new method for finding optimal transitive order
  pricegraph/src/api/price_estimation.rs
  pricegraph/src/orderbook.rs
  pricegraph/src/orderbook/reduced.rs
Labels: merge when green, pricegraph, trivial

#1156 Don't consider dust trades when enumerating transitive orders
  pricegraph/src/api/price_estimation.rs
  pricegraph/src/lib.rs
  pricegraph/src/num.rs
  pricegraph/src/orderbook.rs
  pricegraph/src/orderbook/flow.rs
Labels: merge when green, pricegraph

#1171 Adjust gas price limit based on earned fees
  core/src/bigint_u256.rs
  core/src/driver/stablex_driver.rs
  core/src/lib.rs
  core/src/models/solution.rs
  core/src/orderbook/streamed.rs
  core/src/orderbook/streamed/balance.rs
  core/src/orderbook/streamed/state.rs
  core/src/solution_submission.rs
  driver/src/main.rs
Labels: merge when green

#1185 Fix log message being inverted
  core/src/driver/stablex_driver.rs
Labels: merge when green, trivial

#1193 Only submit solution if gas price cap is at least fast gas price
  core/src/solution_submission.rs
  driver/common.env
Labels: merge when green

#1195 Silence "nonce already used error" temporarily
  core/src/solution_submission.rs
Labels: merge when green

#1180 Use AsyncSleep trait in solution submission
  core/src/contracts/stablex_contract.rs
  core/src/solution_submission.rs
Labels: merge when green

#1202 Add enum for modeling amounts so that atoms are never fractional
  price-estimator/src/filter.rs
  price-estimator/src/models.rs
Labels: Price Estimator, merge when green

#1204 Add configurable event-based orderbook page size
  core/src/contracts/stablex_contract.rs
  core/src/orderbook.rs
  core/src/orderbook/streamed/block_timestamp_reading.rs
  core/src/orderbook/streamed/updating_orderbook.rs
  driver/src/main.rs
  price-estimator/src/main.rs
Labels: merge when green

#1182 Fix race condition when cancelling solution submission transaction
  Cargo.lock
  core/src/solution_submission.rs
Labels: merge when green

#1184 Fix race condition when retrying solution submission transaction
  core/src/contracts/stablex_contract.rs
  core/src/solution_submission.rs
  core/src/solution_submission/retry.rs
Labels: merge when green

#1205 open-solver bump
  .travis.yml
Labels: merge when green

#1199 Filter 0 prices
  core/src/macros.rs
  core/src/models/tokens.rs
  core/src/price_estimation.rs
  core/src/price_estimation/average_price_source.rs
  core/src/price_estimation/clients/dexag.rs
  core/src/price_estimation/clients/generic_client.rs
  core/src/price_estimation/clients/kraken.rs
  core/src/price_estimation/clients/oneinch.rs
  core/src/price_estimation/orderbook_based.rs
  core/src/price_estimation/price_source.rs
  core/src/price_estimation/priority_price_source.rs
  core/src/price_estimation/threaded_price_source.rs
  core/src/token_info/hardcoded.rs
Labels: merge when green

#1208 Log price estimates
  core/src/price_estimation/clients/generic_client.rs
  core/src/price_estimation/clients/kraken.rs
  core/src/price_estimation/orderbook_based.rs
Labels: merge when green

#1209 Simplify select_all future in solution submission retry
  core/src/solution_submission/retry.rs
Labels: merge when green

#1198 implement variable minimum average fee
  Cargo.lock
  README.md
  core/Cargo.toml
  core/src/gas_station.rs
  core/src/price_estimation.rs
  core/src/price_finding.rs
  core/src/price_finding/min_avg_fee.rs
  core/src/price_finding/optimization_price_finder.rs
  driver/common.env
  driver/src/main.rs
Labels: merge when green

#1217 [Easy] Use rinkeby gas staton on rinkeby
  core/src/gas_station.rs
  driver/src/main.rs
Labels: merge when green, trivial

#1214 Update to stable Rust
  .travis.yml
  core/src/contracts/stablex_contract.rs
  price-estimator/docker/Dockerfile
Labels: merge when green, trivial

#1188 E2E historic batch analysis command helpers.
  core/src/history.rs
  core/src/history/batches.rs
  e2e/src/bin/historic_prices.rs
  e2e/src/cmd.rs
  e2e/src/lib.rs
Labels: merge when green, trivial

#1219 Private solver bump
  .travis.yml
Labels: merge when green

#1223 Fix scientific notation in comments and use it where possible
  core/src/price_estimation.rs
  core/src/price_estimation/clients/generic_client.rs
  core/src/price_estimation/clients/kraken.rs
  core/src/price_finding/min_avg_fee.rs
  core/src/token_info.rs
  e2e/tests/stablex_test.rs
  pricegraph/benches/pricegraph.rs
  pricegraph/src/lib.rs
  pricegraph/wasm/README.md
  pricegraph/wasm/tests/nodejs.rs
Labels: cleanup, merge when green, trivial

#1216 Retry submitting solution during network congestion
  core/src/solution_submission.rs
  core/src/solution_submission/retry.rs
Labels: merge when green

#1226 Make solver input/output files directory agnostic
  core/src/driver/scheduler/evm.rs
  core/src/price_finding/optimization_price_finder.rs
  core/src/price_finding/price_finder_interface.rs
Labels: merge when green

#1224 Combine gas price cap and min avg fee computation
  core/src/driver/stablex_driver.rs
  core/src/models/solution.rs
  core/src/price_finding.rs
  core/src/price_finding/min_avg_fee.rs
  core/src/price_finding/optimization_price_finder.rs
  driver/src/main.rs
Labels: merge when green

#1225 Move economic viability trait and make use of gas price cap
  core/src/driver/stablex_driver.rs
  core/src/economic_viability.rs
  core/src/lib.rs
  core/src/price_finding.rs
  core/src/price_finding/optimization_price_finder.rs
  driver/src/main.rs
Labels: merge when green

#1222 Implement get_eth_price
  core/src/economic_viability.rs
  core/src/macros.rs
  core/src/price_estimation.rs
Labels: merge when green

#1215 Allow average price source to be used with references
  core/src/price_estimation/average_price_source.rs
Labels: merge when green

#1181 Apply rounding buffer to pricegraph
  core/src/token_info.rs
  price-estimator/src/filter.rs
  price-estimator/src/infallible_price_source.rs
  price-estimator/src/main.rs
  price-estimator/src/models.rs
  price-estimator/src/orderbook.rs
Labels: Price Estimator, merge when green

#1227 Remove futures-timer dependency
  Cargo.lock
  core/Cargo.toml
  core/src/solution_submission.rs
Labels: merge when green

#1228 Remove unuse dependencies
  Cargo.lock
  core/Cargo.toml
  driver/Cargo.toml
Labels: merge when green

#1183 Implement token price estimation in pricegraph
  core/src/price_estimation/orderbook_based.rs
  e2e/src/bin/historic_prices.rs
  pricegraph/src/api.rs
  pricegraph/src/api/price_source.rs
  pricegraph/src/lib.rs
Labels: merge when green, pricegraph

#1218 Historic trades
  e2e/src/bin/historic_prices.rs
  e2e/src/bin/historic_trades.rs
  pricegraph/src/lib.rs
Labels: merge when green, pricegraph
