Repository gnosis/dex-services, pull requests merged in 2020-10, with the labels that each got.

#1449 Make CI enforce that help output is up to date in README
  .travis.yml
Labels: merge when green

#1451 Do not cap flows for unlimited orders to u128::MAX
  pricegraph/src/api/transitive_orderbook.rs
  pricegraph/src/num.rs
  pricegraph/src/orderbook.rs
  pricegraph/src/orderbook/order.rs
  pricegraph/src/orderbook/user.rs
Labels: merge when green

#1462 Record a metric for when the solver ran out of time
  services-core/src/metrics/solver_metrics.rs
Labels: merge when green

#1477 Add flag to ignore external price sources
  README.md
  driver/src/main.rs
  services-core/src/price_estimation.rs
Labels: merge when green

#1480 Give more control over economic viability computation
  driver/src/main.rs
  services-core/src/driver/stablex_driver.rs
  services-core/src/price_finding.rs
  services-core/src/price_finding/naive_solver.rs
  services-core/src/price_finding/optimization_price_finder.rs
  services-core/src/price_finding/price_finder_interface.rs
Labels: merge when green

#1487 Do not use fallback min_avg_fee in Dynamic strategy
  README.md
  driver/common.env
  driver/src/main.rs
  price-estimator/src/main.rs
  services-core/src/driver/stablex_driver.rs
  services-core/src/economic_viability.rs
Labels: config change

#1490 Ignore trailing whitespace in readme diff
  .travis.yml
  README.md
Labels: trivial

#1493 Add more fine grained gas price estimation method
  services-core/src/economic_viability.rs
  services-core/src/gas_price.rs
  services-core/src/gas_price/eth_node.rs
  services-core/src/gas_price/gas_station.rs
  services-core/src/solution_submission.rs
  services-core/src/solution_submission/retry.rs
Labels: merge when green

#1496 Add GasNow gas price estimator
  services-core/src/gas_price.rs
  services-core/src/gas_price/eth_node.rs
  services-core/src/gas_price/gas_station.rs
  services-core/src/gas_price/gasnow.rs
  services-core/src/gas_price/linear_interpolation.rs
Labels: merge when green

#1481 Add mix of dynamic and static economic viability strategy
  README.md
  driver/src/main.rs
  price-estimator/src/filter.rs
  services-core/src/driver/stablex_driver.rs
  services-core/src/economic_viability.rs
Labels: merge when green

#1494 Refactor Unbounded logic out of bellman ford
  pricegraph/src/graph/shortest_paths.rs
  pricegraph/src/graph/shortest_paths/unbounded.rs
  pricegraph/src/orderbook.rs
Labels: merge when green

#1497 Enforce requirements on interpolation input more explicitly
  services-core/src/gas_price/gasnow.rs
  services-core/src/gas_price/linear_interpolation.rs
Labels: merge when green

#1498 Add ethgasstation gas price estimator
  services-core/src/gas_price.rs
  services-core/src/gas_price/ethgasstation.rs
Labels: merge when green

#1495 Bounded bellman ford
  pricegraph/src/graph/shortest_paths.rs
  pricegraph/src/graph/shortest_paths/bounded.rs
  pricegraph/src/orderbook.rs
Labels: merge when green

#1499 Get rid of dynamic dispatch in bellman ford algorithm
  pricegraph/src/graph/shortest_paths.rs
  pricegraph/src/orderbook.rs
Labels: merge when green
