Repository gnosis/dex-services, pull requests merged in 2020-06, with the labels that each got.

#942 Refactor Io Trait
  driver/src/price_finding/optimization_price_finder.rs
Labels: cleanup, merge when green

#944 Move folder creation into Io trait
  driver/src/price_finding/optimization_price_finder.rs
Labels: cleanup

#945 Make PriceFinding async
  Cargo.lock
  driver/Cargo.toml
  driver/src/driver/stablex_driver.rs
  driver/src/price_finding/naive_solver.rs
  driver/src/price_finding/optimization_price_finder.rs
  driver/src/price_finding/price_finder_interface.rs
Labels: merge when green

#943 [Fuzzing] Create script to run all fuzz targets
  pricegraph/fuzz/fuzz_all_targets.sh
Labels: merge when green

#946 Make StableXDriver async
  driver/src/driver/scheduler/evm.rs
  driver/src/driver/scheduler/system.rs
  driver/src/driver/stablex_driver.rs
Labels: merge when green

#956 Refactor Order to include all order information
  core/src/contracts/stablex_auction_element.rs
  core/src/models/account_state.rs
  core/src/models/order.rs
  core/src/orderbook/auction_data_reader.rs
  core/src/orderbook/onchain_filtered_orderbook.rs
  core/src/orderbook/shadow_orderbook.rs
  core/src/orderbook/streamed/order.rs
  core/src/orderbook/streamed/state.rs
  core/src/orderbook/util.rs
  core/src/price_finding/naive_solver.rs
  core/src/price_finding/optimization_price_finder.rs
Labels: cleanup, merge when green

#953 Generalized Average Price Source
  core/src/price_estimation.rs
  core/src/price_estimation/average_price_source.rs
Labels: merge when green

#959 Add price estimator scaffolding
  Cargo.lock
  Cargo.toml
  price-estimator/Cargo.toml
  price-estimator/README.md
  price-estimator/src/main.rs
Labels: merge when green

#961 Price Estimator: Set up orderbook
  Cargo.lock
  price-estimator/Cargo.toml
  price-estimator/src/main.rs
  price-estimator/src/orderbook.rs
Labels: merge when green

#955 [Pricegraph] Compute overlapping transitive orderbook
  pricegraph/benches/orderbook.rs
  pricegraph/src/graph/path.rs
  pricegraph/src/lib.rs
  pricegraph/src/orderbook.rs
Labels: merge when green

#965 [Pricegraph] Compute transitive orders for token pair
  pricegraph/benches/orderbook.rs
  pricegraph/src/orderbook.rs
Labels: merge when green

#963 Price Estimator: Set up handling of estimated_buy_amount requests
  Cargo.lock
  price-estimator/Cargo.toml
  price-estimator/src/filter.rs
  price-estimator/src/main.rs
  price-estimator/src/orderbook.rs
Labels: merge when green

#975 Fix not running most tests in CI
  Cargo.toml
Labels: merge when green

#968 [Pricegraph] Fix fill order at price
  pricegraph/benches/orderbook.rs
  pricegraph/src/orderbook.rs
Labels: merge when green

#982 Move serialization structs into own module
  price-estimator/src/estimate_buy_amount.rs
  price-estimator/src/filter.rs
  price-estimator/src/main.rs
  price-estimator/src/models.rs
Labels: Price Estimator

#984 Refactor BatchID in its own module
  core/src/driver/scheduler.rs
  core/src/driver/scheduler/evm.rs
  core/src/driver/scheduler/system.rs
  core/src/models.rs
  core/src/models/batch_id.rs
Labels: merge when green

#987 [Pricegraph] Remove unused method
  pricegraph/src/orderbook.rs
Labels: merge when green

#985 Adding a pricegraph based price source
  Cargo.lock
  core/Cargo.toml
  core/src/models/order.rs
  core/src/price_estimation.rs
  core/src/price_estimation/orderbook_based.rs
  core/src/price_estimation/price_source.rs
Labels: merge when green

#991 [Trivial] Making the event based orderbook the default
  driver/src/main.rs
Labels: merge when green

#998 Solver bump: time management
  .travis.yml
Labels: merge when green

#996 Fix overlapping transitive orderbook direction
  pricegraph/src/orderbook.rs
Labels: Price Graph, merge when green

#995 Implement a top-level pricegraph API
  pricegraph/src/lib.rs
  pricegraph/src/num.rs
  pricegraph/src/orderbook.rs
  pricegraph/src/orderbook/order.rs
Labels: Price Graph, merge when green

#997 Add API method for computing transitive orderbook
  pricegraph/src/lib.rs
Labels: Price Graph

#989 Add transititive orderbook request scaffolding
  Cargo.lock
  price-estimator/Cargo.toml
  price-estimator/README.md
  price-estimator/src/filter.rs
  price-estimator/src/main.rs
  price-estimator/src/models.rs
Labels: Price Estimator, merge when green

#1003 [Easy] Downgrade primitive_types lib
  Cargo.lock
  core/Cargo.toml
  core/src/models/order.rs
  core/src/price_estimation/orderbook_based.rs
  price-estimator/src/orderbook.rs
  pricegraph/Cargo.toml
Labels: merge when green

#1001 Fix orders appearing multiple times in the transitive orderbook
  pricegraph/src/orderbook.rs
Labels: Price Graph, merge when green

#1009 Update price estimator to new pricegraph
  price-estimator/src/estimate_buy_amount.rs
  price-estimator/src/filter.rs
  price-estimator/src/main.rs
  price-estimator/src/orderbook.rs
  pricegraph/src/lib.rs
Labels: merge when green

#1013 solver bump: hotfix for faster best ring solver
  .travis.yml
  core/src/price_finding/price_finder_interface.rs
Labels: merge when green

#1011 correctly remove orders with dust remaining amounts
  pricegraph/src/orderbook.rs
Labels: merge when green

#1010 add utility method for computing ask and bid prices
  pricegraph/src/lib.rs
Labels: merge when green

#990 Using the pricegraph based price source
  core/src/price_estimation.rs
  driver/src/main.rs
Labels: merge when green

#994 adjust price estimation to ask for all tokens
  core/src/models/tokens.rs
  core/src/price_estimation.rs
  core/src/price_estimation/data.rs
  core/src/price_estimation/dexag.rs
  core/src/price_estimation/kraken.rs
Labels: merge when green

#1019 Re-enable pricegraph test
  pricegraph/data/mod.rs
Labels: Price Graph

#1018 Fix pricegraph edge cases
  pricegraph/src/lib.rs
  pricegraph/src/orderbook.rs
Labels: Price Graph, merge when green

#1021 Finish implementing transitive orderbook
  Cargo.lock
  price-estimator/Cargo.toml
  price-estimator/src/filter.rs
  price-estimator/src/models.rs
Labels: Price Estimator, merge when green

#1008 Create new type for computing historic exchange informatino
  core/src/history.rs
  core/src/lib.rs
  core/src/orderbook.rs
  core/src/orderbook/streamed.rs
  core/src/orderbook/streamed/orderbook.rs
Labels: merge when green

#1029 fix transitive orderbook ask/bid direction
  price-estimator/src/filter.rs
  pricegraph/src/lib.rs
  pricegraph/src/orderbook.rs
Labels: merge when green

#1015 Deploy price estimator
  .travis.yml
  price-estimator/README.md
  price-estimator/docker/Dockerfile
  price-estimator/docker/deploy.sh
  price-estimator/src/filter.rs
  price-estimator/src/main.rs
Labels: merge when green

#923 Improve pricegraph fuzzing
  Cargo.lock
  pricegraph/fuzz/Cargo.toml
  pricegraph/fuzz/fuzz_targets/orderbook.rs
  pricegraph/fuzz/fuzz_targets/pricegraph.rs
  pricegraph/fuzz/fuzz_targets/util.rs
Labels: Price Graph, merge when green

#1038 Fix transitive orderbook prices being inverted
  pricegraph/src/lib.rs
Labels: merge when green

#1039 Turn threaded price source background thread into async task
  Cargo.lock
  core/Cargo.toml
  core/src/price_estimation/threaded_price_source.rs
Labels: merge when green

#1042 Compute auction state for historic batches
  core/src/orderbook/streamed/orderbook.rs
  core/src/orderbook/streamed/state.rs
Labels: merge when green

#1043 Implement estimated sell amount route
  price-estimator/README.md
  price-estimator/src/filter.rs
  price-estimator/src/models.rs
  pricegraph/src/lib.rs
  pricegraph/src/orderbook.rs
Labels: Price Estimator, Price Graph, merge when green

#1045 Shared HTTP Route Prefixes
  price-estimator/src/filter.rs
Labels: Price Estimator, merge when green

#1049 Merge transitive orders of same price
  price-estimator/src/models.rs
Labels: Price Estimator, merge when green

#1034 Build price estimator image based on alpine
  price-estimator/docker/Dockerfile
Labels: merge when green
