Repository gnosis/dex-services, pull requests merged in 2020-09, with the labels that each got.

#1382 More async_trait conversions
  Cargo.lock
  price-estimator/Cargo.toml
  price-estimator/src/filter.rs
  services-core/src/driver/stablex_driver.rs
  services-core/src/economic_viability.rs
  services-core/src/orderbook.rs
  services-core/src/orderbook/filtered_orderbook.rs
  services-core/src/orderbook/streamed/updating_orderbook.rs
  services-core/src/price_estimation.rs
  services-core/src/price_estimation/threaded_price_source.rs
  services-core/src/price_finding/optimization_price_finder.rs
  services-core/src/solution_submission.rs
  services-core/src/token_info.rs
  services-core/src/token_info/cached.rs
  services-core/src/token_info/hardcoded.rs
  services-core/src/token_info/onchain.rs
Labels: merge when green

#1388 Improve benchmarking
  pricegraph/benches/pricegraph.rs
  pricegraph/src/orderbook.rs
  pricegraph/src/orderbook/map.rs
  pricegraph/src/orderbook/order.rs
  pricegraph/src/orderbook/user.rs
Labels: merge when green, trivial

#1390 move benchmarking to its own crate
  Cargo.lock
  Cargo.toml
  pricegraph/Cargo.toml
  pricegraph/README.md
  pricegraph/bench/Cargo.toml
  pricegraph/bench/pricegraph.rs
  pricegraph/data/Cargo.toml
  pricegraph/data/bin/Cargo.toml
  pricegraph/data/bin/convert.rs
  pricegraph/data/bin/fetch.rs
  pricegraph/data/lib.rs
  pricegraph/fuzz/Cargo.toml
  pricegraph/src/api.rs
  pricegraph/src/encoding.rs
  pricegraph/src/orderbook/map.rs
  pricegraph/src/test.rs
  pricegraph/wasm/Cargo.toml
  pricegraph/wasm/tests/nodejs.rs
Labels: merge when green, trivial

#1393 [Easy] update readme & gitignore
  .gitignore
  README.md
Labels: merge when green

#1392 Update the default log filter after `core` name change
  driver/src/main.rs
  price-estimator/src/main.rs
Labels: merge when green, trivial

#1385 Move StableXContract to async_trait
  services-core/src/contracts/stablex_contract.rs
  services-core/src/driver/scheduler/evm.rs
  services-core/src/driver/scheduler/system.rs
  services-core/src/solution_submission.rs
Labels: merge when green

#1389 More async_trait conversions
  price-estimator/src/orderbook.rs
  services-core/src/contracts/stablex_contract/search_batches.rs
  services-core/src/driver/scheduler/evm.rs
  services-core/src/driver/scheduler/system.rs
  services-core/src/driver/stablex_driver.rs
  services-core/src/orderbook/streamed/block_timestamp_reading.rs
  services-core/src/price_estimation.rs
  services-core/src/price_estimation/average_price_source.rs
  services-core/src/price_estimation/clients/dexag/api.rs
  services-core/src/price_estimation/clients/generic_client.rs
  services-core/src/price_estimation/clients/kraken.rs
  services-core/src/price_estimation/clients/kraken/api.rs
  services-core/src/price_estimation/clients/oneinch/api.rs
  services-core/src/price_estimation/orderbook_based.rs
  services-core/src/price_estimation/price_source.rs
  services-core/src/price_estimation/priority_price_source.rs
  services-core/src/price_estimation/threaded_price_source.rs
  services-core/src/price_finding/naive_solver.rs
  services-core/src/price_finding/optimization_price_finder.rs
  services-core/src/price_finding/price_finder_interface.rs
  services-core/src/token_info/hardcoded.rs
Labels: merge when green

#1384 implement transitive order iterator
  pricegraph/src/orderbook.rs
  pricegraph/src/orderbook/iter.rs
  pricegraph/src/orderbook/reduced.rs
Labels: merge when green

#1386 use new transitive order iterator
  pricegraph/src/api/price_estimation.rs
  pricegraph/src/api/transitive_orderbook.rs
  pricegraph/src/orderbook.rs
  pricegraph/src/orderbook/reduced.rs
Labels: merge when green

#1395 Change weight special value
  pricegraph/fuzz/fuzz_targets/util.rs
  pricegraph/src/encoding.rs
  pricegraph/src/orderbook/weight.rs
Labels: merge when green

#1397 Price estimator metrics
  price-estimator/src/filter.rs
  price-estimator/src/main.rs
  price-estimator/src/metrics.rs
Labels: merge when green

#1400 New best ask and bid API for Pricegraph
  price-estimator/src/filter.rs
  pricegraph/src/api.rs
  pricegraph/src/api/price_estimation.rs
  pricegraph/src/api/transitive_orderbook.rs
Labels: merge when green

#1402 Allow setting fixed min-avg-fee-per-order
  driver/src/main.rs
Labels: config change, merge when green

#1408 [Trivial] More generic logging
  services-core/src/driver/scheduler/evm.rs
Labels: merge when green

#1403 [EASY] Runtime argumentss; default to fallback
  README.md
  driver/src/main.rs
Labels: config change, merge when green

#1401 consistent dust trade handling
  pricegraph/src/api/price_estimation.rs
Labels: merge when green

#1410 Add minimum order size to openapi docs
  price-estimator/openapi.yml
Labels: merge when green

#1411 Add network id parameter to price estimator
  price-estimator/src/main.rs
Labels: config change, merge when green

#1413 Implement `arg_enum` macro
  README.md
  driver/common-mainnet.env
  driver/common-rinkeby.env
  driver/common.env
  driver/docker-compose.best-ring-solver.yml
  driver/docker-compose.open-solver.yml
  driver/docker-compose.private-solver.yml
  driver/docker/rust/release/open_solver/Dockerfile
  driver/docker/rust/release/private_solver/Dockerfile
  driver/src/main.rs
  e2e/README.md
  services-core/src/driver/scheduler.rs
  services-core/src/macros.rs
  services-core/src/price_finding/price_finder_interface.rs
Labels: config change, merge when green

#1412 Factor out duplicated econonomic viability struct creation
  driver/src/main.rs
  price-estimator/src/main.rs
  services-core/src/economic_viability.rs
Labels: merge when green

#1391 Add query parameter to disable rounding buffer
  price-estimator/openapi.yml
  price-estimator/src/amounts_at_price.rs
  price-estimator/src/filter.rs
  price-estimator/src/models/query.rs
  price-estimator/src/orderbook.rs
Labels: merge when green

#1419 [xDAI] Make EthPricing native token agnostic
  README.md
  driver/src/main.rs
  price-estimator/src/filter.rs
  price-estimator/src/main.rs
  price-estimator/src/orderbook.rs
  services-core/src/economic_viability.rs
  services-core/src/price_estimation.rs
Labels: merge when green

#1417 Pricegraph: Store order remaining amount and user balances as integers
  pricegraph/src/api/price_estimation.rs
  pricegraph/src/lib.rs
  pricegraph/src/num.rs
  pricegraph/src/orderbook.rs
  pricegraph/src/orderbook/flow.rs
  pricegraph/src/orderbook/order.rs
  pricegraph/src/orderbook/user.rs
  pricegraph/src/orderbook/weight.rs
Labels: merge when green, pricegraph

#1416 Automatically determine chain id through web3
  driver/src/main.rs
  price-estimator/src/main.rs
  services-core/src/contracts.rs
  services-core/src/contracts/stablex_contract.rs
  services-core/src/gas_price.rs
  services-core/src/gas_price/gas_station.rs
  services-core/src/token_info/onchain.rs
Labels: merge when green

#1421 Filter orders with buy token == sell token
  pricegraph/src/orderbook.rs
Labels: merge when green, pricegraph

#1423 [Easy] Update contracts to v0.4.3
  contracts/artifacts/BatchExchange.json
  contracts/artifacts/BatchExchangeViewer.json
  contracts/src/bin/vendor.rs
Labels: merge when green

#1426 [Easy] Runtime argument names aligned with corresponding env vars
  README.md
  driver/common-mainnet.env
  driver/common-rinkeby.env
  driver/common.env
  driver/src/main.rs
  price-estimator/src/main.rs
Labels: config change, merge when green

#1429 fix README help
  README.md
Labels: documentation, merge when green, trivial

#1428 Modifies how open solver is called.
  .travis.yml
  services-core/src/price_finding/price_finder_interface.rs
Labels: merge when green
